name: Build and Release EXE

# Воркфлоу запускается только тогда, когда ты создаешь новый релиз (публикуешь таг)
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-python: '3.14' # Укажи свою версию Python, если нужно

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install numpy


    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "DSR" --icon=NONE main.py


    # 5. Загружаем готовый EXE в созданный релиз GitHub
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: dist/DSR.exe # Путь к готовому файлу (имя будет как у твоего скрипта)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
